version: '3'
services:
  react-ui:
    build:
      context: ..
      dockerfile: devops/Dockerfile
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ../:/app
      - /app/node_modules
